version: '3.8'

services:
  my-app:
    build:
      context: .
      args:
        NODE_ENV: ${NODE_ENV}
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
