version: '3.8'

services:
  my-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    env_file:
      - .env
    # Remove volumes in production!
    # volumes:
    #   - .:/app
    #   - /app/node_modules
